### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jnoordsij**
This PR updates all dependencies, devDependencies and peerDependencies to latest versions.

It also adds `webpack` as `peerDependency`, to prevent 'missing peer dependency' warnings when installing this with the latest yarn.

I've split the different updates in separate commits, so it's easier to leave out some dependencies if wanted to have slightly more version compatibility.

### CODE REVIEW

**Comment by jnoordsij** [comment]
@agentschmitt any update on this? 😇

**Comment by agentschmitt** [comment]
@jnoordsij sorry i will need to take a look at this, as i also made some update in branch @next for vue-cli-5 already and need to resolve conflicts first.

**Comment by jnoordsij** [comment]
Ah, that's fine! I'll check if I can rebase this onto `next` then.

**Comment by agentschmitt** [comment]
@jnoordsij sorry i accidently closed the pr by merging the next branch to master.
i thought it is time to release just version 5.0 without prerelease.
if you want you can reopen the pr, update of dependencies and also peerDependency looked good to me.

**Pull request closed without merging**
